// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/demo.proto

package com.nonpool.proto;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageName = 1;</code>
   */
  java.lang.String getMessageName();
  /**
   * <code>string messageName = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageNameBytes();

  /**
   * <code>bytes payload = 15;</code>
   */
  com.google.protobuf.ByteString getPayload();
}
